### ISSUE TITLE
Clean stale branches

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/onchain#44]

**Comment by 0xTranqui** [comment]
honest question what do u think we do about stale branches like these? this is like iconic code int he story of AP even tho obvi we dont need it anymore cc @Valcoholics 

<img width="554" alt="Screenshot 2023-07-30 at 11 18 46 PM" src="https://github.com/public-assembly/onchain/assets/93691906/c2ef18a2-92ea-42f7-9c76-39b09a7abebd">

**Comment by Valcoholics** [comment]
theres more context of the significance of the token uri minter in the forum, it's a really long thread that Dain even hopped into, i think you can delete the branch and turn it into a post for the open blog

https://forum.public---assembly.com/t/new-pa-onchain-module-tokenuriminter/

for the others i dont remember that much on it. 

edit: scratch that i do remember artifact machine because there are posts on all of these branches. 

so what do you prefer? context stay on github or plan to migrate posts to the future dev blog

**Comment by 0xTranqui** [comment]
i just realized that all the cool stuff i want to save is actually in the up to date branch in the zora-modules folder. so we are ok. mass deletion event incoming

**Comment by salieflewis** [comment]
Closing this. Thanks @0xTranqui
